server:
  port: 6021
spring:
  application:
    name: order
  zipkin:
    base-url: http://152.136.206.111:9411
  sleuth:
    sampler:
      probability: 1
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

