server:
  port: 6009
spring:
  application:
    name: turbine
turbine:
  aggregator:
    cluster-config: default
  app-config: ORDER,PRODUCTION,USER,STORES
  cluster-name-expression: "'default'"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/