server:
  port: 6041
spring:
  application:
    name: user
  zipkin:
    base-url: http://152.136.206.111:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/

